/**
 * Catalogos oficiales del SAT (Complemento Carta Porte), compartidos entre
 * Unidades (configuracion vehicular del vehiculo motriz) y Remolques
 * (subtipo de remolque/semirremolque). Se usan como el "Tipo de unidad" /
 * "Tipo de remolque" de cada catalogo para que la clasificacion ya calce
 * con la clave que despues pide el CFDI de Carta Porte.
 */

export interface ClaveSat {
  clave: string;
  descripcion: string;
}

/** c_UsoCFDI -- para que efecto fiscal solicita el cliente el comprobante (Facturacion). */
export const USO_CFDI_SAT: ClaveSat[] = [
  { clave: 'G01', descripcion: 'Adquisicion de mercancias' },
  { clave: 'G02', descripcion: 'Devoluciones, descuentos o bonificaciones' },
  { clave: 'G03', descripcion: 'Gastos en general' },
  { clave: 'I01', descripcion: 'Construcciones' },
  { clave: 'I02', descripcion: 'Mobiliario y equipo de oficina por inversiones' },
  { clave: 'I03', descripcion: 'Equipo de transporte' },
  { clave: 'I04', descripcion: 'Equipo de computo y accesorios' },
  { clave: 'I05', descripcion: 'Dados, troqueles, moldes, matrices y otros activos' },
  { clave: 'I06', descripcion: 'Comunicaciones telefonicas' },
  { clave: 'I07', descripcion: 'Comunicaciones satelitales' },
  { clave: 'I08', descripcion: 'Otra maquinaria y equipo' },
  { clave: 'D01', descripcion: 'Honorarios medicos, dentales y gastos hospitalarios' },
  { clave: 'D02', descripcion: 'Gastos medicos por incapacidad o discapacidad' },
  { clave: 'D03', descripcion: 'Gastos funerales' },
  { clave: 'D04', descripcion: 'Donativos' },
  { clave: 'D05', descripcion: 'Intereses reales pagados por creditos hipotecarios (casa habitacion)' },
  { clave: 'D06', descripcion: 'Aportaciones voluntarias al SAR' },
  { clave: 'D07', descripcion: 'Primas por seguros de gastos medicos' },
  { clave: 'D08', descripcion: 'Gastos de transportacion escolar obligatoria' },
  { clave: 'D09', descripcion: 'Depositos en cuentas para el ahorro, pensiones' },
  { clave: 'D10', descripcion: 'Pagos por servicios educativos (colegiaturas)' },
  { clave: 'S01', descripcion: 'Sin efectos fiscales' },
  { clave: 'CP01', descripcion: 'Pagos' },
  { clave: 'CN01', descripcion: 'Nomina' },
];

/** c_ConfigAutotransporte -- configuracion vehicular del vehiculo motriz (Unidades). Fuente: catalogo oficial SAT Carta Porte 3.1 (34 claves). */
export const CONFIG_AUTOTRANSPORTE_SAT: ClaveSat[] = [
  { clave: 'C2', descripcion: 'Camión Unitario (2 llantas en el eje delantero y 4 llantas en el eje trasero)' },
  { clave: 'C2R2', descripcion: 'Camión-Remolque (6 llantas en el camión y 8 llantas en remolque)' },
  { clave: 'C2R3', descripcion: 'Camión-Remolque (6 llantas en el camión y 12 llantas en remolque)' },
  { clave: 'C3', descripcion: 'Camión Unitario (2 llantas en el eje delantero y 6 o 8 llantas en los dos ejes traseros)' },
  { clave: 'C3R2', descripcion: 'Camión-Remolque (10 llantas en el camión y 8 llantas en remolque)' },
  { clave: 'C3R3', descripcion: 'Camión-Remolque (10 llantas en el camión y 12 llantas en remolque)' },
  { clave: 'GPLATA', descripcion: 'Grúa de Plataforma Tipo A' },
  { clave: 'GPLATB', descripcion: 'Grúa de Plataforma Tipo B' },
  { clave: 'GPLATC', descripcion: 'Grúa de Plataforma Tipo C' },
  { clave: 'GPLATD', descripcion: 'Grúa de Plataforma Tipo D' },
  { clave: 'GPLUTA', descripcion: 'Grúa de Pluma Tipo A' },
  { clave: 'GPLUTB', descripcion: 'Grúa de Pluma Tipo B' },
  { clave: 'GPLUTC', descripcion: 'Grúa de Pluma Tipo C' },
  { clave: 'GPLUTD', descripcion: 'Grúa de Pluma Tipo D' },
  { clave: 'OTROEVGP', descripcion: 'Especializado de carga Voluminosa y/o Gran Peso' },
  { clave: 'OTROSG', descripcion: 'Servicio de Grúas' },
  { clave: 'T2S1', descripcion: 'Tractocamión Articulado (6 llantas en el tractocamión, 4 llantas en el semirremolque)' },
  { clave: 'T2S1R2', descripcion: 'Tractocamión Semirremolque-Remolque (6 llantas en el tractocamión, 4 llantas en el semirremolque y 8 llantas en el remolque)' },
  { clave: 'T2S1R3', descripcion: 'Tractocamión Semirremolque-Remolque (6 llantas en el tractocamión, 4 llantas en el semirremolque y 12 llantas en el remolque)' },
  { clave: 'T2S2', descripcion: 'Tractocamión Articulado (6 llantas en el tractocamión, 8 llantas en el semirremolque)' },
  { clave: 'T2S2R2', descripcion: 'Tractocamión Semirremolque-Remolque (6 llantas en el tractocamión, 8 llantas en el semirremolque y 8 llantas en el remolque)' },
  { clave: 'T2S2S2', descripcion: 'Tractocamión Semirremolque-Semirremolque (6 llantas en el tractocamión, 8 llantas en el semirremolque delantero y 8 llantas en el semirremolque trasero)' },
  { clave: 'T2S3', descripcion: 'Tractocamión Articulado (6 llantas en el tractocamión, 12 llantas en el semirremolque)' },
  { clave: 'T3S1', descripcion: 'Tractocamión Articulado (10 llantas en el tractocamión, 4 llantas en el semirremolque)' },
  { clave: 'T3S1R2', descripcion: 'Tractocamión Semirremolque-Remolque (10 llantas en el tractocamión, 4 llantas en el semirremolque y 8 llantas en el remolque)' },
  { clave: 'T3S1R3', descripcion: 'Tractocamión Semirremolque-Remolque (10 llantas en el tractocamión, 4 llantas en el semirremolque y 12 llantas en el remolque)' },
  { clave: 'T3S2', descripcion: 'Tractocamión Articulado (10 llantas en el tractocamión, 8 llantas en el semirremolque)' },
  { clave: 'T3S2R2', descripcion: 'Tractocamión Semirremolque-Remolque (10 llantas en el tractocamión, 8 llantas en el semirremolque y 8 llantas en el remolque)' },
  { clave: 'T3S2R3', descripcion: 'Tractocamión Semirremolque-Remolque (10 llantas en el tractocamión, 8 llantas en el semirremolque y 12 llantas en el remolque)' },
  { clave: 'T3S2R4', descripcion: 'Tractocamión Semirremolque-Remolque (10 llantas en el tractocamión, 8 llantas en el semirremolque y 16 llantas en el remolque)' },
  { clave: 'T3S2S2', descripcion: 'Tractocamión Semirremolque-Semirremolque (10 llantas en el tractocamión, 8 llantas en el semirremolque delantero y 8 llantas en el semirremolque trasero)' },
  { clave: 'T3S3', descripcion: 'Tractocamión Articulado (10 llantas en el tractocamión, 12 llantas en el semirremolque)' },
  { clave: 'T3S3S2', descripcion: 'Tractocamión Semirremolque-Semirremolque (10 llantas en el tractocamión, 12 llantas en el semirremolque delantero y 8 llantas en el semirremolque trasero)' },
  { clave: 'VL', descripcion: 'Vehículo ligero de carga (2 llantas en el eje delantero y 2 llantas en el eje trasero)' },
];

/** c_SubTipoRem -- subtipo de remolque/semirremolque (Remolques). Fuente: catalogo oficial SAT Carta Porte 3.1 (31 claves). */
export const SUBTIPO_REMOLQUE_SAT: ClaveSat[] = [
  { clave: 'CTR001', descripcion: 'Caballete' },
  { clave: 'CTR002', descripcion: 'Caja' },
  { clave: 'CTR003', descripcion: 'Caja Abierta' },
  { clave: 'CTR004', descripcion: 'Caja Cerrada' },
  { clave: 'CTR005', descripcion: 'Caja De Recolección Con Cargador Frontal' },
  { clave: 'CTR006', descripcion: 'Caja Refrigerada' },
  { clave: 'CTR007', descripcion: 'Caja Seca' },
  { clave: 'CTR008', descripcion: 'Caja Transferencia' },
  { clave: 'CTR009', descripcion: 'Cama Baja o Cuello Ganso' },
  { clave: 'CTR010', descripcion: 'Chasis Portacontenedor' },
  { clave: 'CTR011', descripcion: 'Convencional De Chasis' },
  { clave: 'CTR012', descripcion: 'Equipo Especial' },
  { clave: 'CTR013', descripcion: 'Estacas' },
  { clave: 'CTR014', descripcion: 'Góndola Madrina' },
  { clave: 'CTR015', descripcion: 'Grúa Industrial' },
  { clave: 'CTR016', descripcion: 'Grúa' },
  { clave: 'CTR017', descripcion: 'Integral' },
  { clave: 'CTR018', descripcion: 'Jaula' },
  { clave: 'CTR019', descripcion: 'Media Redila' },
  { clave: 'CTR020', descripcion: 'Pallet o Celdillas' },
  { clave: 'CTR021', descripcion: 'Plataforma' },
  { clave: 'CTR022', descripcion: 'Plataforma Con Grúa' },
  { clave: 'CTR023', descripcion: 'Plataforma Encortinada' },
  { clave: 'CTR024', descripcion: 'Redilas' },
  { clave: 'CTR025', descripcion: 'Refrigerador' },
  { clave: 'CTR026', descripcion: 'Revolvedora' },
  { clave: 'CTR027', descripcion: 'Semicaja' },
  { clave: 'CTR028', descripcion: 'Tanque' },
  { clave: 'CTR029', descripcion: 'Tolva' },
  { clave: 'CTR031', descripcion: 'Volteo' },
  { clave: 'CTR032', descripcion: 'Volteo Desmontable' },
];

/** c_TipoPermiso -- tipo de permiso SCT/ATFS del autotransporte (Carta Porte). Fuente: catalogo oficial SAT Carta Porte 3.1 (26 claves). */
export const TIPO_PERMISO_SCT: ClaveSat[] = [
  { clave: 'TPAF01', descripcion: 'Autotransporte Federal de carga general.' },
  { clave: 'TPAF02', descripcion: 'Transporte privado de carga.' },
  { clave: 'TPAF03', descripcion: 'Autotransporte Federal de Carga Especializada de materiales y residuos peligrosos.' },
  { clave: 'TPAF04', descripcion: 'Transporte de automóviles sin rodar en vehículo tipo góndola.' },
  { clave: 'TPAF05', descripcion: 'Transporte de carga de gran peso y/o volumen de hasta 90 toneladas.' },
  { clave: 'TPAF06', descripcion: 'Transporte de carga especializada de gran peso y/o volumen de más 90 toneladas.' },
  { clave: 'TPAF07', descripcion: 'Transporte Privado de materiales y residuos peligrosos.' },
  { clave: 'TPAF08', descripcion: 'Autotransporte internacional de carga de largo recorrido.' },
  { clave: 'TPAF09', descripcion: 'Autotransporte internacional de carga especializada de materiales y residuos peligrosos de largo recorrido.' },
  { clave: 'TPAF10', descripcion: 'Autotransporte Federal de Carga General cuyo ámbito de aplicación comprende la franja fronteriza con Estados Unidos.' },
  { clave: 'TPAF11', descripcion: 'Autotransporte Federal de Carga Especializada cuyo ámbito de aplicación comprende la franja fronteriza con Estados Unidos.' },
  { clave: 'TPAF12', descripcion: 'Servicio auxiliar de arrastre en las vías generales de comunicación.' },
  { clave: 'TPAF13', descripcion: 'Servicio auxiliar de servicios de arrastre, arrastre y salvamento, y depósito de vehículos en las vías generales de comunicación.' },
  { clave: 'TPAF14', descripcion: 'Servicio de paquetería y mensajería en las vías generales de comunicación.' },
  { clave: 'TPAF15', descripcion: 'Transporte especial para el tránsito de grúas industriales con peso máximo de 90 toneladas.' },
  { clave: 'TPAF16', descripcion: 'Servicio federal para empresas arrendadoras servicio público federal.' },
  { clave: 'TPAF17', descripcion: 'Empresas trasladistas de vehículos nuevos.' },
  { clave: 'TPAF18', descripcion: 'Empresas fabricantes o distribuidoras de vehículos nuevos.' },
  { clave: 'TPAF19', descripcion: 'Autorización expresa para circular en los caminos y puentes de jurisdicción federal con configuraciones de tractocamión doblemente articulado.' },
  { clave: 'TPAF20', descripcion: 'Autotransporte Federal de Carga Especializada de fondos y valores.' },
  { clave: 'TPTA01', descripcion: 'Concesión y/o autorización para el servicio regular nacional y/o internacional para empresas mexicanas' },
  { clave: 'TPTA02', descripcion: 'Permiso para el servicio aéreo regular de empresas extranjeras' },
  { clave: 'TPTA03', descripcion: 'Permiso para el servicio nacional e internacional no regular de fletamento' },
  { clave: 'TPTA04', descripcion: 'Permiso para el servicio nacional e internacional no regular de taxi aéreo' },
  { clave: 'TPTM01', descripcion: 'Permiso temporal para navegación de cabotaje' },
  { clave: 'TPXX00', descripcion: 'Permiso no contemplado en el catálogo.' },
];

/** c_TipoEmbalaje -- tipo de embalaje de la mercancia (Complemento Carta Porte). Fuente: catalogo oficial SAT Carta Porte 3.1 (59 claves). */
export const TIPOS_EMBALAJE_SAT: ClaveSat[] = [
  { clave: '1A1', descripcion: 'Bidones (Tambores) de Acero 1 de tapa no desmontable' },
  { clave: '1A2', descripcion: 'Bidones (Tambores) de Acero 1 de tapa desmontable' },
  { clave: '1B1', descripcion: 'Bidones (Tambores) de Aluminio de tapa no desmontable' },
  { clave: '1B2', descripcion: 'Bidones (Tambores) de Aluminio de tapa desmontable' },
  { clave: '1D', descripcion: 'Bidones (Tambores) de Madera contrachapada' },
  { clave: '1G', descripcion: 'Bidones (Tambores) de Cartón' },
  { clave: '1H1', descripcion: 'Bidones (Tambores) de Plástico de tapa no desmontable' },
  { clave: '1H2', descripcion: 'Bidones (Tambores) de Plástico de tapa desmontable' },
  { clave: '1N1', descripcion: 'Bidones (Tambores) de Metal que no sea acero ni aluminio de tapa no desmontable' },
  { clave: '1N2', descripcion: 'Bidones (Tambores) de Metal que no sea acero ni aluminio de tapa desmontable' },
  { clave: '3A1', descripcion: 'Jerricanes (Porrones) de Acero de tapa no desmontable' },
  { clave: '3A2', descripcion: 'Jerricanes (Porrones) de Acero de tapa desmontable' },
  { clave: '3B1', descripcion: 'Jerricanes (Porrones) de Aluminio de tapa no desmontable' },
  { clave: '3B2', descripcion: 'Jerricanes (Porrones) de Aluminio de tapa desmontable' },
  { clave: '3H1', descripcion: 'Jerricanes (Porrones) de Plástico de tapa no desmontable' },
  { clave: '3H2', descripcion: 'Jerricanes (Porrones) de Plástico de tapa desmontable' },
  { clave: '4A', descripcion: 'Cajas de Acero' },
  { clave: '4B', descripcion: 'Cajas de Aluminio' },
  { clave: '4C1', descripcion: 'Cajas de Madera natural ordinaria' },
  { clave: '4C2', descripcion: 'Cajas de Madera natural de paredes a prueba de polvos (estancas a los pulverulentos)' },
  { clave: '4D', descripcion: 'Cajas de Madera contrachapada' },
  { clave: '4F', descripcion: 'Cajas de Madera reconstituida' },
  { clave: '4G', descripcion: 'Cajas de Cartón' },
  { clave: '4H1', descripcion: 'Cajas de Plástico Expandido' },
  { clave: '4H2', descripcion: 'Cajas de Plástico Rígido' },
  { clave: '5H1', descripcion: 'Sacos (Bolsas) de Tejido de plástico sin forro ni revestimientos interiores' },
  { clave: '5H2', descripcion: 'Sacos (Bolsas) de Tejido de plástico a prueba de polvos (estancos a los pulverulentos)' },
  { clave: '5H3', descripcion: 'Sacos (Bolsas) de Tejido de plástico resistente al agua' },
  { clave: '5H4', descripcion: 'Sacos (Bolsas) de Película de plástico' },
  { clave: '5L1', descripcion: 'Sacos (Bolsas) de Tela sin forro ni revestimientos interiores' },
  { clave: '5L2', descripcion: 'Sacos (Bolsas) de Tela a prueba de polvos (estancos a los pulverulentos)' },
  { clave: '5L3', descripcion: 'Sacos (Bolsas) de Tela resistentes al agua' },
  { clave: '5M1', descripcion: 'Sacos (Bolsas) de Papel de varias hojas' },
  { clave: '5M2', descripcion: 'Sacos (Bolsas) de Papel de varias hojas, resistentes al agua' },
  { clave: '6HA1', descripcion: 'Envases y embalajes compuestos de Recipiente de plástico, con bidón (tambor) de acero' },
  { clave: '6HA2', descripcion: 'Envases y embalajes compuestos de Recipiente de plástico, con una jaula o caja de acero' },
  { clave: '6HB1', descripcion: 'Envases y embalajes compuestos de Recipiente de plástico, con un bidón (tambor) exterior de aluminio' },
  { clave: '6HB2', descripcion: 'Envases y embalajes compuestos de Recipiente de plástico, con una jaula o caja de aluminio' },
  { clave: '6HC', descripcion: 'Envases y embalajes compuestos de Recipiente de plástico, con una caja de madera' },
  { clave: '6HD1', descripcion: 'Envases y embalajes compuestos de Recipiente de plástico, con un bidón (tambor) de madera contrachapada' },
  { clave: '6HD2', descripcion: 'Envases y embalajes compuestos de Recipiente de plástico, con una caja de madera contrachapada' },
  { clave: '6HG1', descripcion: 'Envases y embalajes compuestos de Recipiente de plástico, con un bidón (tambor) de cartón' },
  { clave: '6HG2', descripcion: 'Envases y embalajes compuestos de Recipiente de plástico, con una caja de cartón' },
  { clave: '6HH1', descripcion: 'Envases y embalajes compuestos de Recipiente de plástico, con un bidón (tambor) de plástico' },
  { clave: '6HH2', descripcion: 'Envases y embalajes compuestos de Recipiente de plástico, con caja de plástico rígido' },
  { clave: '6PA1', descripcion: 'Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con un bidón (tambor) de acero' },
  { clave: '6PA2', descripcion: 'Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con una jaula o una caja de acero' },
  { clave: '6PB1', descripcion: 'Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con un bidón (tambor) exterior de aluminio' },
  { clave: '6PB2', descripcion: 'Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con una jaula o una caja de aluminio' },
  { clave: '6PC', descripcion: 'Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con una caja de madera' },
  { clave: '6PD1', descripcion: 'Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con bidón (tambor) de madera contrachapada' },
  { clave: '6PD2', descripcion: 'Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con canasta de mimbre' },
  { clave: '6PG1', descripcion: 'Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con un bidón (tambor) de cartón' },
  { clave: '6PG2', descripcion: 'Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con una caja de cartón' },
  { clave: '6PH1', descripcion: 'Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con un envase y embalaje de plástico expandido' },
  { clave: '6PH2', descripcion: 'Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con un envase y embalaje de plástico rígido' },
  { clave: '7H1', descripcion: 'Bultos de Plástico' },
  { clave: '7L1', descripcion: 'Bultos de Tela' },
  { clave: 'Z01', descripcion: 'No aplica' },
];

/** c_SectorCOFEPRIS -- sector regulado por COFEPRIS de la mercancia (Carta Porte, opcional). Fuente: catalogo oficial SAT Carta Porte 3.1 (5 claves). */
export const SECTOR_COFEPRIS_SAT: ClaveSat[] = [
  { clave: '01', descripcion: 'Medicamento' },
  { clave: '02', descripcion: 'Precursores y químicos de uso dual' },
  { clave: '03', descripcion: 'Psicotrópicos y estupefacientes' },
  { clave: '04', descripcion: 'Sustancias tóxicas' },
  { clave: '05', descripcion: 'Plaguicidas y fertilizantes' },
];

/** c_TipoMateria -- tipo de materia de la mercancia regulada por COFEPRIS (Carta Porte, opcional). Fuente: catalogo oficial SAT Carta Porte 3.1 (5 claves). */
export const TIPO_MATERIA_COFEPRIS_SAT: ClaveSat[] = [
  { clave: '01', descripcion: 'Materia prima' },
  { clave: '02', descripcion: 'Materia procesada' },
  { clave: '03', descripcion: 'Materia terminada (producto terminado)' },
  { clave: '04', descripcion: 'Materia para la industria manufacturera' },
  { clave: '05', descripcion: 'Otra' },
];

/** c_ObjetoImp -- si el concepto es objeto de impuesto (usado en Conceptos de Facturacion). */
export const OBJETO_IMPUESTO_SAT: ClaveSat[] = [
  { clave: '01', descripcion: 'No objeto de impuesto.' },
  { clave: '02', descripcion: 'Si objeto de impuesto.' },
  { clave: '03', descripcion: 'Si objeto del impuesto y no obligado al desglose.' },
  { clave: '04', descripcion: 'Si objeto del impuesto y no causa impuesto.' },
];
